# Generated by Django 4.1.3 on 2022-11-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=6)),
            ],
        ),
    ]
